name: layout
description: >-
  Sample app from "Building Layouts", https://docs.flutter.dev/ui/layout.
version: 1.0.0+1

environment:
  sdk:  ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  dotted_border: ^2.1.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/news/
    - assets/staduim/
    - assets/teams/
